# Generated by Django 5.0.4 on 2026-04-07 21:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='disciplines/', verbose_name='Иконка')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Дисциплина',
                'verbose_name_plural': 'Дисциплины',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('tier', models.CharField(choices=[('title', 'Титульный спонсор'), ('main', 'Главный партнёр'), ('official', 'Официальный партнёр'), ('technical', 'Технический партнёр')], max_length=20, verbose_name='Уровень')),
                ('logo', models.ImageField(upload_to='partners/', verbose_name='Логотип')),
                ('website', models.URLField(verbose_name='Сайт')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Партнёр',
                'verbose_name_plural': 'Партнёры',
                'ordering': ['tier', 'order'],
            },
        ),
        migrations.CreateModel(
            name='TeamInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField(verbose_name='О команде')),
                ('founded_year', models.IntegerField(default=2015, verbose_name='Год основания')),
                ('headquarters', models.CharField(default='Москва, Россия', max_length=200, verbose_name='Штаб-квартира')),
                ('total_earnings', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Общий призовой фонд ($)')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='team/', verbose_name='Логотип')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='team/', verbose_name='Баннер')),
                ('twitter', models.URLField(blank=True, verbose_name='Twitter')),
                ('instagram', models.URLField(blank=True, verbose_name='Instagram')),
                ('youtube', models.URLField(blank=True, verbose_name='YouTube')),
                ('twitch', models.URLField(blank=True, verbose_name='Twitch')),
                ('vk', models.URLField(blank=True, verbose_name='VK')),
                ('telegram', models.URLField(blank=True, verbose_name='Telegram')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Email для связи')),
            ],
            options={
                'verbose_name': 'Информация о команде',
                'verbose_name_plural': 'Информация о команде',
            },
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название турнира')),
                ('place', models.IntegerField(choices=[(1, '1 место'), (2, '2 место'), (3, '3 место'), (4, 'Топ-4'), (8, 'Топ-8'), (16, 'Топ-16')], verbose_name='Место')),
                ('prize_pool', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Призовой фонд ($)')),
                ('prize_won', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Выигрыш ($)')),
                ('date', models.DateField(verbose_name='Дата')),
                ('image', models.ImageField(blank=True, null=True, upload_to='achievements/', verbose_name='Изображение')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='core.discipline', verbose_name='Дисциплина')),
            ],
            options={
                'verbose_name': 'Достижение',
                'verbose_name_plural': 'Достижения',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tournament', models.CharField(max_length=200, verbose_name='Турнир')),
                ('opponent', models.CharField(max_length=200, verbose_name='Соперник')),
                ('opponent_logo', models.ImageField(blank=True, null=True, upload_to='opponents/', verbose_name='Логотип соперника')),
                ('date', models.DateTimeField(verbose_name='Дата и время')),
                ('status', models.CharField(choices=[('upcoming', 'Предстоящий'), ('live', 'Идёт'), ('finished', 'Завершён')], default='upcoming', max_length=20, verbose_name='Статус')),
                ('score_team', models.IntegerField(default=0, verbose_name='Счёт Team Spirit')),
                ('score_opponent', models.IntegerField(default=0, verbose_name='Счёт соперника')),
                ('stream_url', models.URLField(blank=True, verbose_name='Ссылка на трансляцию')),
                ('vod_url', models.URLField(blank=True, verbose_name='Ссылка на запись')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='core.discipline', verbose_name='Дисциплина')),
            ],
            options={
                'verbose_name': 'Матч',
                'verbose_name_plural': 'Матчи',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Заголовок')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('category', models.CharField(choices=[('announcement', 'Анонс'), ('result', 'Результат'), ('roster', 'Ростер'), ('interview', 'Интервью'), ('other', 'Другое')], default='other', max_length=20, verbose_name='Категория')),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/', verbose_name='Изображение')),
                ('excerpt', models.TextField(max_length=500, verbose_name='Краткое описание')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Избранное')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Просмотры')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('discipline', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news', to='core.discipline', verbose_name='Дисциплина')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=100, verbose_name='Никнейм')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('role', models.CharField(choices=[('carry', 'Керри'), ('mid', 'Мидер'), ('offlane', 'Оффлейнер'), ('support', 'Саппорт'), ('captain', 'Капитан'), ('coach', 'Тренер'), ('analyst', 'Аналитик'), ('manager', 'Менеджер')], max_length=20, verbose_name='Роль')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='players/', verbose_name='Фото')),
                ('country', models.CharField(default='Россия', max_length=100, verbose_name='Страна')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('join_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата вступления')),
                ('bio', models.TextField(blank=True, verbose_name='Биография')),
                ('twitch', models.URLField(blank=True, verbose_name='Twitch')),
                ('twitter', models.URLField(blank=True, verbose_name='Twitter')),
                ('instagram', models.URLField(blank=True, verbose_name='Instagram')),
                ('is_active', models.BooleanField(default=True, verbose_name='В составе')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='core.discipline', verbose_name='Дисциплина')),
            ],
            options={
                'verbose_name': 'Игрок',
                'verbose_name_plural': 'Игроки',
                'ordering': ['discipline', 'nickname'],
            },
        ),
    ]
